(function(){'use strict';var last=null,SK='caderno-vivo-state-v5';
function sanitize(str){var d=document.createElement('div');d.textContent=String(str||'');return d.innerHTML;}
function getState(){try{return JSON.parse(localStorage.getItem('caderno-vivo-state-v5')||'{}')||{};}catch(e){return {};}}
function toast(m,t){if(window.CvButtons&&window.CvButtons.toast)window.CvButtons.toast(m,t||'ok');}
function download(n,c,type){var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c||''],{type:type||'text/plain;charset=utf-8'}));a.download=n;a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},0);}

function injectCSS(){if(document.getElementById('estudio-styles'))return;var st=document.createElement('style');st.id='estudio-styles';st.textContent='.estudio-form,.estudio-resultado{background:rgba(0,0,0,.3);border:1px solid #4c1d95;border-radius:16px;color:#e2e8f0;padding:18px;margin-bottom:16px}.estudio-form label{display:block;color:#a78bfa;font-size:12px;font-weight:700;margin:8px 0}.estudio-form textarea,.estudio-form input{width:100%;box-sizing:border-box;background:rgba(0,0,0,.35);border:1px solid #4c1d95;border-radius:10px;color:#e2e8f0;padding:10px}.estudio-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.estudio-btn{background:#7c3aed;border:0;border-radius:10px;color:white;padding:10px 16px;cursor:pointer;margin:4px 4px 0 0}.estudio-btn:disabled{opacity:.6;cursor:wait}.estudio-muted{color:#94a3b8;font-size:13px}.estudio-resultado pre{white-space:pre-wrap}@media(max-width:600px){.estudio-grid{grid-template-columns:1fr}}';document.head.appendChild(st);}
function renderUI(c){(c.querySelector('.cv-view-body')||c).innerHTML='<section class="estudio-form"><label>Prompt / inspiração</label><textarea id="mus-prompt" rows="5" placeholder="Conte a história, tema ou frase inicial..."></textarea><div class="estudio-grid"><div><label>Gênero</label><input id="mus-genre" placeholder="MPB, gospel, pop..."></div><div><label>Mood</label><input id="mus-mood" placeholder="esperançoso, romântico..."></div><div><label>Tom</label><input id="mus-key" placeholder="C, G, Am..."></div><div><label>BPM</label><input id="mus-tempo" type="number" placeholder="90"></div></div><p id="mus-status" class="estudio-muted">Pronto para gerar letra, cifras e notas de produção.</p><button id="mus-go" class="estudio-btn">Gerar música</button><button id="mus-capture" class="estudio-btn">Captura rápida</button><button id="mus-save" class="estudio-btn">Salvar versão</button><button id="mus-export" class="estudio-btn">Exportar .txt</button></section><section class="estudio-resultado"><div id="mus-result" class="estudio-muted">Estado vazio: nenhuma música gerada ainda.</div></section>';}
function sections(d){var out='',lyrics=(d&&d.lyrics)||{},chords=(d&&d.chords)||{};function toStr(v){if(typeof v==='string')return v;if(Array.isArray(v))return v.join('\n');if(v&&typeof v==='object')return Object.values(v).join('\n');return String(v||'');}Object.keys(lyrics).forEach(function(k){out+='['+k+']\n'+(chords[k]?toStr(chords[k])+'\n':'')+toStr(lyrics[k])+'\n\n';});return out||JSON.stringify(d||last||{},null,2);}
function render(c,d){last=d||last;if(!c.querySelector('#mus-result'))renderUI(c);var r=c.querySelector('#mus-result');if(!last){r.textContent='Estado vazio: nenhuma música gerada ainda.';return;}r.innerHTML='<h3>'+sanitize(last.title||'Nova música')+'</h3><p><b>Estilo:</b> '+sanitize(last.style||'')+' · <b>Tom:</b> '+sanitize(last.key||'')+' · <b>BPM:</b> '+sanitize(last.tempo||'')+'</p><pre>'+sanitize(sections(last))+'</pre><p><b>Notas:</b> '+sanitize(last.production_notes||'')+'</p>';}
function save(d){var s=getState();s.works=Array.isArray(s.works)?s.works:[];s.works.unshift({id:'ai-'+Date.now(),title:d.title||'Música sem título',status:'em produção',createdAt:Date.now(),updatedAt:Date.now(),music:d,lyrics:sections(d)});localStorage.setItem(SK,JSON.stringify(s));if(typeof renderWorks==='function')renderWorks();document.dispatchEvent(new CustomEvent('cv:obra-salva',{detail:{obra:s.works[0]}}));document.dispatchEvent(new CustomEvent('cv:state-changed'));}
function refresh(){var c=document.getElementById('cv-criar');if(c)render(c,last);}
function v(id){var e=document.getElementById(id);return e?e.value:'';}function st(t){var e=document.getElementById('mus-status');if(e)e.textContent=t;}
function bindEvents(c){if(c.dataset.estudioBound==='true')return;c.dataset.estudioBound='true';c.addEventListener('click',async function(e){var id=e.target&&e.target.id;if(id==='mus-go'){var b=e.target,p=v('mus-prompt').trim();if(!p){toast('Escreva uma inspiração.','aviso');return;}b.disabled=true;st('Carregando: compondo com IA...');try{var r=await fetch('/api/generate-music',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:p,genre:v('mus-genre'),mood:v('mus-mood'),key:v('mus-key'),tempo:v('mus-tempo')})});var d=await r.json();if(!r.ok)throw new Error(d.error||'Falha');last=d;render(c,d);save(d);st('Sucesso: música criada e salva.');}catch(err){st('Erro amigável: não foi possível gerar agora. Tente novamente em instantes.');document.getElementById('mus-result').textContent='Não conseguimos falar com a IA agora. Sua ideia continua aqui: '+p;}finally{b.disabled=false;}} if(id==='mus-export')download('musica-caderno-vivo.txt',(last&&((last.title||'Música')+'\n\n'+sections(last)))||''); if(id==='mus-capture'){document.getElementById('mus-prompt').focus();st('Captura rápida ativa: registre sua ideia.');} if(id==='mus-save'){if(last)save(last);st(last?'Versão salva com sucesso.':'Gere uma música antes de salvar a versão.');}});}
function init(){var c=document.getElementById('cv-criar');if(!c)return;injectCSS();renderUI(c);render(c,last);bindEvents(c);}
document.addEventListener('cv:navigate',function(e){if(e&&e.detail&&e.detail.to==='cv-criar')init();});document.addEventListener('cv:state-changed',refresh);document.addEventListener('cv:obra-salva',refresh);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else setTimeout(init,300);window.EstudioMusical={init:init,render:render,refresh:refresh,bindEvents:bindEvents,getState:getState};})();
