(function(){ 'use strict';
 var ready=false,last=null, SK='caderno-vivo-state-v5'; function toast(m,t){ if(window.CvButtons&&window.CvButtons.toast) window.CvButtons.toast(m,t||'ok'); }
 function style(){ if(document.getElementById('cv-ai-style'))return; var s=document.createElement('style'); s.id='cv-ai-style'; s.textContent='.cv-ai{background:rgba(0,0,0,.3);border:1px solid #4c1d95;border-radius:16px;color:#e2e8f0;padding:18px;margin-bottom:16px}.cv-ai label{display:block;color:#a78bfa;font-size:12px;font-weight:700;margin:8px 0}.cv-ai textarea,.cv-ai input,.cv-ai select{width:100%;box-sizing:border-box;background:rgba(0,0,0,.35);border:1px solid #4c1d95;border-radius:10px;color:#e2e8f0;padding:10px}.cv-ai-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.cv-ai-btn{background:#7c3aed;border:0;border-radius:10px;color:white;padding:10px 16px;cursor:pointer}.cv-ai-btn:disabled{opacity:.6;cursor:wait}.cv-ai-muted{color:#94a3b8;font-size:13px}.cv-ai pre{white-space:pre-wrap;color:#e2e8f0}@media(max-width:800px){.cv-ai-grid{grid-template-columns:1fr}}'; document.head.appendChild(s); }
 function init(){ if(ready)return; var root=document.getElementById('cv-criar'); if(!root)return; ready=true; style(); root.querySelector('.cv-view-body').innerHTML='<section class="cv-ai"><label>Prompt / inspiração</label><textarea id="mus-prompt" rows="5" placeholder="Conte a história, tema ou frase inicial..."></textarea><div class="cv-ai-grid"><div><label>Gênero</label><input id="mus-genre" placeholder="MPB, gospel, pop..."></div><div><label>Mood</label><input id="mus-mood" placeholder="esperançoso, romântico..."></div><div><label>Tom</label><input id="mus-key" placeholder="C, G, Am..."></div><div><label>BPM</label><input id="mus-tempo" type="number" placeholder="90"></div></div><p id="mus-status" class="cv-ai-muted">Gere letra, cifras e notas de produção com IA real.</p><button id="mus-go" class="cv-ai-btn">Gerar música</button> <button id="mus-export" class="cv-ai-btn">Exportar .txt</button></section><section class="cv-ai"><div id="mus-result" class="cv-ai-muted">Nenhuma música gerada ainda.</div></section>'; bind(); }
 function bind(){ var b=document.getElementById('mus-go'); b.onclick=async function(){ var prompt=v('mus-prompt').trim(); if(!prompt){toast('Escreva uma inspiração.','aviso');return;} b.disabled=true; st('Compondo com Groq...'); try{ var r=await fetch('/api/generate-music',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:prompt,genre:v('mus-genre'),mood:v('mus-mood'),key:v('mus-key'),tempo:v('mus-tempo')})}); var d=await r.json(); if(!r.ok) throw new Error(d.error||'Falha ao gerar música'); last=d; render(d); save(d); st('Música criada e salva.'); toast('Música gerada e salva.','ia'); }catch(e){st(e.message);toast(e.message,'erro');} finally{b.disabled=false;} }; document.getElementById('mus-export').onclick=function(){download('musica-caderno-vivo.txt',toText(last));}; }
 function render(d){ document.getElementById('mus-result').innerHTML='<h3 style="color:#e2e8f0">'+esc(d.title||'Nova música')+'</h3><p><b>Estilo:</b> '+esc(d.style||'')+' · <b>Tom:</b> '+esc(d.key||'')+' · <b>BPM:</b> '+esc(d.tempo||'')+'</p><pre>'+esc(sections(d.lyrics,d.chords))+'</pre><p><b>Notas:</b> '+esc(d.production_notes||'')+'</p>'; }
 function sections(lyrics,chords){ var out=''; lyrics=lyrics||{}; chords=chords||{}; Object.keys(lyrics).forEach(function(k){ out+='['+k+']\n'; if(chords[k]) out+=chords[k]+'\n'; out+=lyrics[k]+'\n\n';}); return out||JSON.stringify(last,null,2); }
 function save(d){ var s={}; try{s=JSON.parse(localStorage.getItem(SK)||'{}');}catch(e){} s.works=Array.isArray(s.works)?s.works:[]; s.works.unshift({id:'ai-'+Date.now(),title:d.title||'Música sem título',status:'em produção',createdAt:Date.now(),updatedAt:Date.now(),music:d}); localStorage.setItem(SK,JSON.stringify(s)); }
 function toText(d){return d?((d.title||'Música')+'\n\n'+sections(d.lyrics,d.chords)+'\nNotas: '+(d.production_notes||'')):'';} function v(id){return document.getElementById(id).value;} function st(t){document.getElementById('mus-status').textContent=t;} function esc(s){return String(s||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c];});} function download(n,c){var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type:'text/plain;charset=utf-8'}));a.download=n;a.click();URL.revokeObjectURL(a.href);} document.addEventListener('cv:navigate',function(e){if(e.detail.to==='cv-criar')init();}); if(document.getElementById('cv-criar')?.classList.contains('active'))init();
})();
