(function(){ 'use strict';
  var ready=false, last='';
  function toast(m,t){ if(window.CvButtons&&window.CvButtons.toast) window.CvButtons.toast(m,t||'ok'); }
  function css(){return '<style>.cv-ai{background:rgba(0,0,0,.3);border:1px solid #4c1d95;border-radius:16px;color:#e2e8f0;padding:18px;margin-bottom:16px}.cv-ai label{display:block;color:#a78bfa;font-size:12px;font-weight:700;margin:8px 0}.cv-ai textarea,.cv-ai input,.cv-ai select{width:100%;box-sizing:border-box;background:rgba(0,0,0,.35);border:1px solid #4c1d95;border-radius:10px;color:#e2e8f0;padding:10px}.cv-ai-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.cv-ai-btn{background:#7c3aed;border:0;border-radius:10px;color:white;padding:10px 16px;cursor:pointer}.cv-ai-btn:disabled{opacity:.6;cursor:wait}.cv-ai-muted{color:#94a3b8;font-size:13px}@media(max-width:800px){.cv-ai-grid{grid-template-columns:1fr}}</style>';}
  function init(){ if(ready) return; var root=document.getElementById('cv-internacional'); if(!root) return; ready=true; root.querySelector('.cv-view-body').innerHTML=css()+'<section class="cv-ai"><div class="cv-ai-grid"><div><label>Original</label><textarea id="intl-src" rows="14" placeholder="Cole a letra original..."></textarea></div><div><label>Tradução</label><textarea id="intl-out" rows="14" readonly placeholder="A tradução musical aparecerá aqui..."></textarea></div></div><div class="cv-ai-grid"><div><label>Idioma de destino</label><select id="intl-lang">'+['inglês','espanhol','francês','italiano','alemão','japonês','coreano','mandarim','árabe','hebraico','hindi','bengali','russo','ucraniano','polonês','holandês','sueco','norueguês','turco','grego','swahili','zulu','português europeu'].map(function(l){return '<option>'+l+'</option>';}).join('')+'</select></div><div><label>Estilo</label><select id="intl-style"><option>natural</option><option>poética</option><option>literal</option><option>adaptação</option></select></div></div><p class="cv-ai-muted" id="intl-status">Preserva rima, métrica e emoção.</p><button id="intl-go" class="cv-ai-btn">Traduzir</button> <button id="intl-export" class="cv-ai-btn" type="button">Exportar .txt</button></section>'; bind(); }
  function bind(){ var go=document.getElementById('intl-go'); go.onclick=async function(){ var text=document.getElementById('intl-src').value.trim(); if(!text){toast('Cole uma letra para traduzir.','aviso');return;} go.disabled=true; status('Traduzindo com IA...'); try{ var r=await fetch('/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:text,targetLanguage:val('intl-lang'),sourceLanguage:'português do Brasil',style:val('intl-style')})}); var d=await r.json(); if(!r.ok) throw new Error(d.error||'Falha na tradução'); last=d.translation||''; document.getElementById('intl-out').value=last; status('Tradução pronta.'); toast('Tradução concluída.','ia'); }catch(e){status(e.message);toast(e.message,'erro');} finally{go.disabled=false;} };
  document.getElementById('intl-export').onclick=function(){ download('traducao-caderno-vivo.txt', last||document.getElementById('intl-out').value); }; }
  function val(id){return document.getElementById(id).value;} function status(t){document.getElementById('intl-status').textContent=t;} function download(n,c){var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type:'text/plain;charset=utf-8'}));a.download=n;a.click();URL.revokeObjectURL(a.href);} document.addEventListener('cv:navigate',function(e){if(e.detail.to==='cv-internacional')init();}); if(document.getElementById('cv-internacional')?.classList.contains('active')) init();
})();
